from enum import Enum

class CamposNutrientes(Enum):
    ID = 'Nr.'
    DESCRICAO = 'Descrição'
    UMIDADE = 'Umidade (%)'
    ENERGIA_KCAL = 'Energia (kcal)'
    ENERGIA_KJ = 'Energia (kJ)'
    PROTEINA = 'Proteína (g)'
    LIPIDEOS = 'Lipídeos (g)'
    COLESTEROL = 'Colesterol (mg)'
    CARBOIDRATOS = 'Carboidrato (g)'
    FIBRA_ALIMENTAR = 'Fibra alimentar (g)'
    CINZAS = 'Cinzas (g)'
    CALCIO = 'Cálcio (mg)'
    MAGNESIO = 'Magnésio (mg)'
    MANGANES = 'Manganês (mg)'
    FOSFORO = 'Fósforo (mg)'
    FERRO = 'Ferro (mg)'
    SODIO = 'Sódio (mg)'
    POTASSIO = 'Potássio (mg)'
    COBRE = 'Cobre (mg)'
    ZINCO = 'Zinco (mg)'
    RETINOL = 'Retinol (mcg)'
    RE = 'RE (mcg)'
    RAE = 'RAE (mcg)'
    TIAMINA = 'Tiamina (mg)'
    RIBOFLAVINA = 'Riboflavina (mg)'
    PIRIDOXINA = 'Piridoxina (mg)'
    NIACINA = 'Niacina (mg)'
    VITAMINA_C = 'Vitamina C (mg)'
