nutrientes = {
    'umidade': '%',
    'energia_kcal': 'kcal',
    'energia_kj' : 'kJ',
    'proteina': 'g',
    'lipideos': 'g',
    'colesterol': 'mg',
    'carboidrato': 'g',
    'fibra_alimentar': 'g',
    'cinzas': 'g',
    'calcio': 'mg',
    'magnesio': 'mg',
    'manganes': 'mg',
    'fosforo': 'mg',
    'sodio': 'mg',
    'potassio': 'mg',
    'cobre': 'mg',
    'zinco': 'mg',
    'retinol': 'mcg',
    're': 'mcg',
    'rae': 'mcg',
    'tiamina': 'mg',
    'riboflavina': 'mg',
    'piridoxina': 'mg',
    'niacina': 'mg',
    'vitamina_c': 'mg'
}
